### ISSUE TITLE
Uncaught TypeError: inherits is not a function

### ISSUE THREAD

**Issue by khatekar** [jessetane/queue#19] opened 2016-05-12 07:24 UTC
I got the following error while importing the 'queue' module in my angularjs code.
var queue = require('queue');

Uncaught TypeError: inherits is not a function  
it's targeting n error in ../node_modules/queue/index.js line no.19

notify.js:38 Uncaught Error: Uncaught TypeError: inherits is not a function

inherits(Queue, EventEmitter); queue/index.js +19

**Comment by jessetane** [comment] 2016-05-12 12:45
How are you installing this module? The inherits library is a dependency, but your package manager should have installed it for you automatically...

**Comment by khatekar** [comment] 2016-05-12 14:59
It installed the inherits library, but still, it's showing the above error.

**Comment by jessetane** [comment] 2016-05-12 15:00
You mentioned angular, so I assume you're using this in the browser? What are you using for a build tool?

**Comment by khatekar** [comment] 2016-05-12 15:02
I am using Angularjs and nodejs.

**Comment by jessetane** [comment] 2016-05-12 15:02
Where are you seeing this error? In the browser, right?

**Comment by khatekar** [comment] 2016-05-12 18:38
I am seeing this error in the browser' Console. The queue package gets installed properly, I see it install its dependencies.

**Comment by khatekar** [comment] 2016-05-12 18:40
../node_modules/queue/index.js line no.19

**Comment by jessetane** [comment] 2016-05-12 18:41
How are you building your javascript for the client? Browserify? Webpack?

**Comment by khatekar** [comment] 2016-05-12 18:43
ah, sorry I think I missed your question. I am using Webpack.

**Comment by jessetane** [comment] 2016-05-12 18:55
Unfortunately I'm not super familiar with webpack, but my guess is that it is just not pulling the dependency in...

**Comment by khatekar** [comment] 2016-05-12 19:00
As I mentioned above, it installed the dependency library (inherits). Anyways, thanks for looking into it. I will try to re-install node modules.

**Comment by jessetane** [comment] 2016-05-12 19:02
So npm installs the dependencies, but webpack is responsible for resolving them getting them all bundled into one file.

**Comment by jessetane** [comment] 2016-05-12 19:02
If node_modules/inherits exists, then the problem is with webpack and not npm.

**Comment by khatekar** [comment] 2016-05-12 19:03
Yes, I was thinking that one, will check to reinstalling the node module. I will let you know.

**Comment by jessetane** [comment] 2016-05-17 01:56
Were you able to resolve this issue?

**Comment by jessetane** [comment] 2016-05-19 20:57
Closing since this problem was probably webpack related

**Closed by jessetane** 2016-05-19 20:57 UTC
